# Module manifest for module 'DevTools'
#
# Generated by: Radek Zahradník
# Generated on: 04.10.2023


@{

# Script module or binary module file associated with this manifest.
RootModule = 'CityaDevTools'

# Version number of this module.
ModuleVersion = '1.9.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '26425f40-b799-43e4-9757-d4c4e0f4740b'

# Author of this module
Author = 'Radek Zahradník'

# Company or vendor of this module
CompanyName = 'Citya'

# Copyright statement for this module
Copyright = '(c) Citya. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.3.3'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('*')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes =
@'
v1.0.0: (2023-10-18)
- Add Start-PortForwarding
- Add Install-GoogleDbTooling

v1.0.1: (2023-10-22)
- Fix missing "$" in variable name causing FileNotFound exception

v1.1.0: (2023-10-22)
- Update path resolution to calculate with installation to ProgramFiles

v1.1.1: (2023-11-16)
- Fix parameter validation
- Add parameter switch for development/production

v1.2.0: (2023-11-20)
- Fix code formatting
- Add Find-NuGetPackage function
- Add Get-NuGetPackage function
- Add Find-NuGetPackage function

v1.3.0: (2023-12-02)
- Add Remove-CityaDatabase function

v1.4.0: (2024-01-18)
- Add New-AccessToken function
- Add Remove-CityaDatabase function

v1.5.0: (2024-06-11)
- Add Test-AllocatorRequest
- Add Add-CityaMigration
- Add Get-CityaMigrationScript
- Add Update-CityaDatabase
- Add Remove-CityaDatabase function

v1.5.1: (2024-07-02)
- Fix missing space in Update-CityaDatabase
- Add Remove-CityaDatabase function

v1.6.0: (2024-07-05)
- Ädd Update-CityaBackendReleaseTag
- Ädd Push-CityaBackendReleaseTag
- Ädd Remove-CityaDatabase function

v1.7.0: (2024-10-08)
- Add Test-AllocatorRequest
- Ädd Remove-CityaDatabase function

v1.7.1: (2024-10-14)
- Fix path in Test-AllocatorRequest
- Ädd Remove-CityaDatabase function

v1.8.0: (2024-10-14)
- Add new service area allocators to Invoke-AllocatorRequest

v1.9.0: (2024-10-15)
- Update Push-CityaBackendReleaseTag with new release draft

v1.9.1: (2025-01-15)
- Update Install-GoogleDbTooling with new Google SDK installation path
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

